In [1]:
import os
import numpy as np
folder = "/media/yipeng/data/movie_2021/Movie_Analysis/data"
patientNums = ['431', '433', '435', '436', '439', '441', '444', '445', '452']
suffix = "features_mat_regions_clean.npy" 

In [2]:
def parse_squeeze(x):
    res = []
    for xx in x:
        res.append(xx[0])
    return res

In [3]:
all_r = set()
for p in patientNums:
    test_folder = os.path.join(folder, p)
    region_fn = os.path.join(test_folder, suffix)
    region = parse_squeeze(np.load(region_fn, allow_pickle=True))
    all_r = all_r.union(set(region))

In [4]:
import pandas as pd
df = pd.DataFrame()
df["region_name"] = list(all_r)

In [30]:
df.to_csv("region_name.csv")

In [31]:
######split data

In [6]:
def create_dict(ls1, ls2):
    res = {}
    for idx in range(len(ls1)):
        res[ls1[idx]] = ls2[idx]
    return res
def parse_region(mapping, region_name):
    res = []
    for r in region_name:
        res.append(mapping[r])
    return np.array(res)


In [60]:
data_foler = "/media/yipeng/data/movie_2021/Movie_Analysis/mem_test"
df = pd.read_csv("region_name.csv")
mapping = create_dict(df["region_name"].values, df["MTL"].values)
res_folder = "/media/yipeng/data/movie_2021/Movie_Analysis/data_MTL_split"
for p in patientNums:
    test_folder = os.path.join(folder, p)
    region_fn = os.path.join(test_folder, suffix)
    data_fn = os.path.join(data_foler, p, "feature.npy")
    region = parse_squeeze(np.load(region_fn, allow_pickle=True))
    MTL_mask = parse_region(mapping, region)
    print(MTL_mask)
    data = np.load(data_fn, allow_pickle=True)
    data_MTL = np.copy(data)
    index = np.where(MTL_mask ==1)[0]
    data_MTL[:,index,:] = data_MTL[:,index,:]*0
    data_no_MTL = np.copy(data)
    index = np.where(MTL_mask == 0)[0]
    data_no_MTL[:,index,:] = data_no_MTL[:,index,:]*0

    path_MTL = os.path.join(res_folder, 'data_MTL', p)
    path_noMTL = os.path.join(res_folder, 'data_noMTL', p)
    #os.mkdir(path_MTL)
    #os.mkdir(path_noMTL)
    np.save(os.path.join(path_MTL ,'features.npy'), data_MTL)
    np.save(os.path.join(path_noMTL ,'features.npy'), data_no_MTL)

[1 1 1 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[1 1 1 1 1 1 1 1 1 1 0 0 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[1 1 1 1 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 0
 0 0 0 0 0 0 0 0 0 0 0 0]
[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0]
[1 1 1 1 1 1 0 0]
[1 1 1 1 1 1 1 1 1 1 1 1 0 0 0 0 0 0]
[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0]
[1 1 1 1 1 1 1 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 0 0 0 0 0 0 0]
[1 1 1 1 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]


In [26]:
patientNums = ['431', '435', '436',  '441']
data_foler = "/media/yipeng/data/movie_2021/Movie_Analysis/mem_test"
data_foler = "/media/yipeng/data/movie_2021/Movie_Analysis/training_data_1_zero"
df = pd.read_csv("region_name.csv")
mapping = create_dict(df["region_name"].values, df["MTL"].values)
res_folder = "/media/yipeng/data/movie_2021/Movie_Analysis/data_MTL_split"
print("MTL_mean", "MTL_var","no_mean","no_var")
for p in patientNums:
    test_folder = os.path.join(folder, p)
    region_fn = os.path.join(test_folder, suffix)
    data_fn = os.path.join(data_foler, p, "feature.npy")
    region = parse_squeeze(np.load(region_fn, allow_pickle=True))
    MTL_mask = parse_region(mapping, region)
    #print(region)
    #print(MTL_mask)
    data = np.load(data_fn, allow_pickle=True)
    #data_MTL = np.copy(data)
    no_mtl_index = np.where(MTL_mask ==0)[0]
    #data_MTL[:,index,:] = data_MTL[:,index,:]*0
    #data_no_MTL = np.copy(data)
    mtl_index = np.where(MTL_mask == 1)[0]
    
    mtl_data = np.concatenate(data[:,mtl_index,:], 1)
    no_mtl_data = np.concatenate(data[:,no_mtl_index,:], 1)

    mtl_data = mtl_data
    no_mtl_data = no_mtl_data
    
    print(p, np.round(np.mean(mtl_data), 3), np.round(np.var(mtl_data), 3),np.round(np.mean(no_mtl_data), 3), np.round(np.var(no_mtl_data), 3))
    #MLT_region = np.array(region)[index]
    #print("region",MLT_region)
    #path_MTL = os.path.join(res_folder, 'data_MTL', p)
    #path_noMTL = os.path.join(res_folder, 'data_noMTL', p)
    #os.mkdir(path_MTL)
    #os.mkdir(path_noMTL)
    #np.save(os.path.join(path_MTL ,'features.npy'), data_MTL)
    #np.save(os.path.join(path_noMTL ,'features.npy'), data_no_MTL)

MTL_mean MTL_var no_mean no_var
431 0.116 0.197 0.373 0.412
435 0.098 0.099 0.296 0.442
436 0.429 0.671 0.127 0.173
441 0.048 0.042 0.155 0.151


In [27]:
aa = np.load("/media/yipeng/data/movie_2021/Movie_Analysis/data_MTL_split/data_MTL/431/features.npy")

In [29]:
np.sum(aa[0], -1)

array([ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        , 22.        ,
        0.        , 13.33333333,  0.66666667, 14.66666667,  6.66666667,
       25.66666667,  8.        ,  7.66666667,  1.33333333,  5.        ,
        1.33333333, 17.        , 16.33333333,  6.66666667,  1.        ,
        1.        , 55.66666667, 11.66666667,  0.        ,  0.66666667,
       13.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        8.        ,  3.33333333, 27.33333333,  2.66666667, 53.66666667,
        4.66666667, 18.        ,  6.66666667, 16.        , 23.33333333,
       19.        , 21.33333333, 10.66666667,  0.        ,  0.        ,
       40.33333333, 10.33333333,  0.66666667,  1.33333333,  0.66666667])

In [31]:
p = "431"
test_folder = os.path.join(folder, p)
region_fn = os.path.join(test_folder, suffix)

In [33]:
region_tag = np.load(region_fn, allow_pickle=True)

In [34]:
region_tag

array([array(['RA'], dtype='<U2'), array(['RA'], dtype='<U2'),
       array(['RA'], dtype='<U2'), array(['RA'], dtype='<U2'),
       array(['RA'], dtype='<U2'), array(['RA'], dtype='<U2'),
       array(['RA'], dtype='<U2'), array(['RA'], dtype='<U2'),
       array(['RA'], dtype='<U2'), array(['RSTA'], dtype='<U4'),
       array(['RSTA'], dtype='<U4'), array(['RSTA'], dtype='<U4'),
       array(['RSTA'], dtype='<U4'), array(['RSTA'], dtype='<U4'),
       array(['RSTA'], dtype='<U4'), array(['RSTA'], dtype='<U4'),
       array(['RSTA'], dtype='<U4'), array(['RSTA'], dtype='<U4'),
       array(['RSTA'], dtype='<U4'), array(['RSTA'], dtype='<U4'),
       array(['RSTA'], dtype='<U4'), array(['RSTP'], dtype='<U4'),
       array(['RSTP'], dtype='<U4'), array(['RSTP'], dtype='<U4'),
       array(['RSTP'], dtype='<U4'), array(['RSTP'], dtype='<U4'),
       array(['RSTP'], dtype='<U4'), array(['RSTP'], dtype='<U4'),
       array(['RSTP'], dtype='<U4'), array(['RSTP'], dtype='<U4'),
       array(