In [1]:
from utilities import *

/media/yipeng/data/movie/Movie_Analysis/Character_TimeStamp_resnet/1.pkl
/media/yipeng/data/movie/Movie_Analysis/Character_TimeStamp_resnet/0.pkl
/media/yipeng/data/movie/Movie_Analysis/Character_TimeStamp_resnet/2.pkl
/media/yipeng/data/movie/Movie_Analysis/Character_TimeStamp_resnet/3.pkl
/media/yipeng/data/movie/Movie_Analysis/draft_result/episode1_character_size.pkl
/media/yipeng/data/movie/Movie_Analysis/draft_result/episode2_character_size.pkl


In [5]:
aa = load_pickle("/media/yipeng/data/movie/Movie_Analysis/final_result_outputs/CNN/figure4_one_step.pkl")

/media/yipeng/data/movie/baseline/10patient_random_model_confusion_mat.pkl


In [2]:
aa = load_pickle("/media/yipeng/data/movie/Movie_Analysis/final_result_inputs/431/regions.pkl")

/media/yipeng/data/movie/Movie_Analysis/final_result_inputs/431/regions.pkl


In [3]:
aa

array(['RA', 'RA', 'RA', 'RA', 'RA', 'RA', 'RA', 'RA', 'RA', 'RA', 'RA',
       'RA', 'RA', 'RMH', 'RMH', 'RMH', 'RSTA', 'RSTA', 'RSTA', 'RSTA',
       'RSTA', 'RSTA', 'RSTA', 'RSTA', 'RSTA', 'RSTA', 'RSTA', 'RSTA',
       'RSTA', 'RSTA', 'RSTP', 'RSTP', 'RSTP', 'RSTP', 'RSTP', 'RSTP',
       'RSTP', 'RSTP', 'RSTP', 'RSTP', 'LST', 'LST', 'LST', 'LST', 'LST',
       'LIP', 'LIP', 'LIP', 'LIP', 'LIP', 'LIP', 'LIP', 'LIP', 'LIP',
       'RSS', 'RSS', 'RSS', 'RSS', 'RSS', 'RSS', 'RSS', 'RSS', 'RIPA',
       'RIPA', 'RIPA', 'RIPA', 'RIPA', 'RIPP', 'RIPP', 'RIPP', 'RIPP',
       'RIPP', 'RIPP', 'RIPP', 'RIPP', 'RIPP'], dtype='<U4')

In [4]:
bb = load_pickle("/media/yipeng/data/movie/Movie_Analysis/final_result_inputs/431/microwire.pkl")

/media/yipeng/data/movie/Movie_Analysis/final_result_inputs/431/microwire.pkl


In [8]:
aa

array(['RA', 'RA', 'RA', 'RA', 'RA', 'RA', 'RA', 'RA', 'RA', 'RA', 'RA',
       'RA', 'RA', 'RMH', 'RMH', 'RMH', 'RSTA', 'RSTA', 'RSTA', 'RSTA',
       'RSTA', 'RSTA', 'RSTA', 'RSTA', 'RSTA', 'RSTA', 'RSTA', 'RSTA',
       'RSTA', 'RSTA', 'RSTP', 'RSTP', 'RSTP', 'RSTP', 'RSTP', 'RSTP',
       'RSTP', 'RSTP', 'RSTP', 'RSTP', 'LST', 'LST', 'LST', 'LST', 'LST',
       'LIP', 'LIP', 'LIP', 'LIP', 'LIP', 'LIP', 'LIP', 'LIP', 'LIP',
       'RSS', 'RSS', 'RSS', 'RSS', 'RSS', 'RSS', 'RSS', 'RSS', 'RIPA',
       'RIPA', 'RIPA', 'RIPA', 'RIPA', 'RIPP', 'RIPP', 'RIPP', 'RIPP',
       'RIPP', 'RIPP', 'RIPP', 'RIPP', 'RIPP'], dtype='<U4')

In [9]:
bb

array([ 2,  3,  3,  5,  5,  6,  6,  6,  7,  7,  8,  8,  8, 10, 14, 15, 17,
       17, 17, 18, 18, 19, 20, 21, 22, 23, 23, 23, 24, 24, 25, 25, 25, 26,
       26, 28, 29, 30, 30, 32, 33, 36, 36, 38, 39, 41, 42, 44, 44, 45, 46,
       47, 48, 48, 50, 50, 52, 53, 53, 54, 55, 56, 58, 59, 60, 62, 62, 65,
       66, 67, 67, 68, 69, 70, 71, 72], dtype=uint8)

In [10]:
cc = load_pickle("/media/yipeng/data/movie/Movie_Analysis/final_result_outputs/LSTM/figure3_preprocess.pkl")

/media/yipeng/data/movie/Movie_Analysis/final_result_outputs/LSTM/figure3_preprocess.pkl


In [16]:
cc["431"]["region_label"]

['baseline', 'LIP', 'LST', 'RA', 'RIPA', 'RIPP', 'RMH', 'RSS', 'RSTA', 'RSTP']

In [20]:
cc["431"]["region_loss"]

array([[0.0876346 , 0.04162066, 0.00826727, 0.04286978],
       [1.13757741, 1.10640538, 0.68051436, 0.56280423],
       [0.26037273, 0.15132682, 0.16581029, 0.2516474 ],
       [0.20216089, 0.09946014, 0.06259374, 0.09158846],
       [0.65486028, 0.28804193, 0.23096063, 0.26438922],
       [0.10617365, 0.04152496, 0.01798644, 0.05283452],
       [0.08741927, 0.04086626, 0.00838913, 0.04271582],
       [0.98731589, 0.63780328, 0.51703951, 0.48601576],
       [1.30800842, 0.83006013, 0.93038711, 1.01650973],
       [1.50434419, 0.98419321, 0.88253308, 0.39394654]])

In [18]:
cc["431"]["region_loss_exp"][0]

array([ 1.14526294e-01,  1.14526294e-01,  1.14526294e-01,  1.14526294e-01,
        1.14526294e-01,  1.14526294e-01, -2.15321712e-04, -2.15321712e-04,
       -2.15321712e-04,  1.22037383e+00,  1.22037383e+00,  1.22037383e+00,
        1.22037383e+00,  1.22037383e+00,  1.22037383e+00,  1.22037383e+00,
        1.22037383e+00,  1.41670959e+00,  1.41670959e+00,  1.41670959e+00,
        1.41670959e+00,  1.41670959e+00,  1.41670959e+00,  1.72738134e-01,
        1.72738134e-01,  1.72738134e-01,  1.72738134e-01,  1.04994281e+00,
        1.04994281e+00,  1.04994281e+00,  1.04994281e+00,  1.04994281e+00,
        1.04994281e+00,  1.04994281e+00,  8.99681296e-01,  8.99681296e-01,
        8.99681296e-01,  8.99681296e-01,  8.99681296e-01,  8.99681296e-01,
        5.67225681e-01,  5.67225681e-01,  5.67225681e-01,  5.67225681e-01,
        1.85390539e-02,  1.85390539e-02,  1.85390539e-02,  1.85390539e-02,
        1.85390539e-02,  1.85390539e-02,  1.85390539e-02,  1.85390539e-02])

In [21]:
cc["431"]["reg_trim"]

array(['RA', 'RA', 'RA', 'RA', 'RA', 'RA', 'RMH', 'RMH', 'RMH', 'RSTA',
       'RSTA', 'RSTA', 'RSTA', 'RSTA', 'RSTA', 'RSTA', 'RSTA', 'RSTP',
       'RSTP', 'RSTP', 'RSTP', 'RSTP', 'RSTP', 'LST', 'LST', 'LST', 'LST',
       'LIP', 'LIP', 'LIP', 'LIP', 'LIP', 'LIP', 'LIP', 'RSS', 'RSS',
       'RSS', 'RSS', 'RSS', 'RSS', 'RIPA', 'RIPA', 'RIPA', 'RIPA', 'RIPP',
       'RIPP', 'RIPP', 'RIPP', 'RIPP', 'RIPP', 'RIPP', 'RIPP'],
      dtype='<U4')

In [22]:
cc["431"]["sum_mircowire_loss_region"]

array([[ 5.89404040e-02,  5.89404040e-02,  5.89404040e-02,
         5.89404040e-02,  5.89404040e-02,  5.89404040e-02,
        -2.24642179e-04, -2.24642179e-04, -2.24642179e-04,
         1.19340671e+00,  1.19340671e+00,  1.19340671e+00,
         1.19340671e+00,  1.19340671e+00,  1.19340671e+00,
         1.19340671e+00,  1.19340671e+00,  1.19271813e+00,
         1.19271813e+00,  1.19271813e+00,  1.19271813e+00,
         1.19271813e+00,  1.19271813e+00,  1.57320532e-01,
         1.57320532e-01,  1.57320532e-01,  1.57320532e-01,
         8.93891435e-01,  8.93891435e-01,  8.93891435e-01,
         8.93891435e-01,  8.93891435e-01,  8.93891435e-01,
         8.93891435e-01,  4.70355547e-01,  4.70355547e-01,
         4.70355547e-01,  4.70355547e-01,  4.70355547e-01,
         4.70355547e-01,  5.06690262e-01,  5.06690262e-01,
         5.06690262e-01,  5.06690262e-01,  1.99433218e-02,
         1.99433218e-02,  1.99433218e-02,  1.99433218e-02,
         1.99433218e-02,  1.99433218e-02,  1.99433218e-0

In [6]:
def cal_f1_score(tp,fp,fn):
    p = 1.0*tp/(tp+fp+10e-5)
    r = 1.0*tp/(tp+fn+10e-5)
    f1 = p*r*2/(p+r+10e-5)
    return f1

In [10]:
import numpy as np 
patientNums = ['431', '433', '435', '436', '439', '441', '442', '444', '445', '452']
for p in patientNums:
    confusion = np.sum(aa[int(p)], axis=0)
    tp = confusion[0,0]
    fp = confusion[0,1]
    fn = confusion[1,0]
    print(p)
    print(cal_f1_score(tp,fp,fn))

431
0.11601635157758164
433
0.11438395938465382
435
0.11578798845978146
436
0.11536145562290827
439
0.11800350472803668
441
0.11577783785358557
442
0.11416843680521255
444
0.11481973015533325
445
0.11370221565655826
452
0.11509731389963734
